### ISSUE TITLE
Error importing DotBashers

### ISSUE THREAD

**Issue by danielmartincraig** [ganeshutah/Jove#1]
Hi Ganesh, I'm in Rick Neff's class at BYUI.  Thanks for letting us use your book.  I have cloned Jove, installed conda, installed graphviz, and i have confirmed that they are working.  

I get an error when I go to run Drive_DFA.ipynb, which says that there is no module named jove.DotBashers.  Do I need to add jove to my PYTHONPATH?  I didn't see it mentioned in the installation instructions and so I thought I would reach out for your help.  Thanks, Daniel Craig
![screenshot from 2019-02-01 20-09-43](https://user-images.githubusercontent.com/13541826/52159191-e5291680-265d-11e9-8585-0af1de3ef232.png)

**Comment by ganeshutah** [comment]
Definitely glad you are using Jove.

Glad you are using the book!

It should work - are you using Windows? If you tell me exactly you did, I
can try and reproduce on Windows or Mac.

BTW feel free to direct email me. (I get busy and don't use "git methods"
to email , track issues, etc that much...)

I don't rely on PythonPath. We wanted to make it work smoothly across Mac,
Linux, and Windows and also make the Post Correspondence problem work (it
calls a compiled binary). After much trial and error, we decided to
literally copy over the "jove/" folders EVERYWHERE. It is ugly but it
works. Reason: inclusion of Jupyter notebooks within Jupyter notebooks is
an advertised feature but did not work once (bug in JSON parsing).

So I generated .py out of all the necessary files (ipynb) and put them all
under Jove

I hope to adjust the install instructions after seeing your issue in
detail. These instructions did work for my current grad class that is using
Jove fine on Windows and Mac.  So not sure what is missing.

If after git clone you don't see "jove/" waiting for you, then there is
something wrong.

Best,
Ganesh

**Comment by danielmartincraig** [comment]
Thanks for the amazingly quick reply!!  I am on Ubuntu 18.04, using Firefox, by the way.

I resolved this by adding a path configuration file in my site-packages directory, and adding __init__.py to the jove directory, like so:

```
cd $(python -m site --user-site)
echo "/home/daniel/Repos/Jove/" > jove.pth

cd $HOME/Repos/Jove/jove/
touch __init__.py
```

After this, Python was able to find the DotBashers module.  

Thanks for your help!!

**Comment by ganeshutah** [comment]
Frankly, very few (if any) in my class used Ubuntu... so this is valuable.
I'll have a student test it, then find it fail, then follow your
instructions and document + push. I'm Ccing Prof. Neff for his info.

(This was the first project where I used github also. Takes time to teach
an old dog some new tricks :-) ).

BTW I've started some UGs with linking Jove and D3 (active documents). This
is to add animation. Another project is to use D3 as a "host" and put in
Jove's logic inside. These are to make Jove easier to install (people like
running things inside Jove).

Glad you sorted it out!

Best,
Ganesh

**Comment by danielmartincraig** [comment]
I believe that the error I got wouldn't have happened if I had been on Python 3 however - I am trying Python 3 with it now, where I believe that it would have worked without the steps I took.  When I wrote this issue I was using Python 2.7

I will let you know what I find.

**Comment by ganeshutah** [comment]
that will be nice to know! thanks! (I am amazed it worked with Python
2.7... prints may barf..)

**Comment by danielmartincraig** [comment]
Indeed, prints did barf!  That was my clue that Python 3 was required haha.  Everything is functioning perfectly now, after doing

```cd $(python3 -m site --user-site)
echo "/home/daniel/Repos/Jove/" > jove.pth
```

and installing ipykernal on both python2 and 3, following these instructions: https://stackoverflow.com/a/38516572/6074048

I am not sure if all of this was required, but now I am able to run Jove with the Python 3 kernel and everything functions wonderfully.

**Comment by ganeshutah** [comment]
Good to know. I'll have my RA Ian (Cc) follow your instructions and update
Jove's install instructions. Thanks!

Feel free to write about other observations.

Best,
Ganesh
